/* ============================================================
   data.js — Dati JSON incorporati per funzionamento offline
   Generato automaticamente da data/ JSON files
   ============================================================ */

window.GNL_DATA = {
  users: [
  {
    "id": "USR-001",
    "nome": "Marco Pellegrini",
    "ruolo": "Operations Manager",
    "email": "m.pellegrini@globalnexus.com",
    "ufficio": "Roma, Italia",
    "stato": "Attivo",
    "data_registrazione": "2019-03-15"
  },
  {
    "id": "USR-002",
    "nome": "Sophie Laurent",
    "ruolo": "Logistics Coordinator",
    "email": "s.laurent@globalnexus.com",
    "ufficio": "Parigi, Francia",
    "stato": "Attivo",
    "data_registrazione": "2020-07-22"
  },
  {
    "id": "USR-003",
    "nome": "James Whitfield",
    "ruolo": "Senior Analyst",
    "email": "j.whitfield@globalnexus.com",
    "ufficio": "Londra, UK",
    "stato": "Attivo",
    "data_registrazione": "2018-11-05"
  },
  {
    "id": "USR-004",
    "nome": "Yuki Tanaka",
    "ruolo": "Regional Director APAC",
    "email": "y.tanaka@globalnexus.com",
    "ufficio": "Tokyo, Giappone",
    "stato": "Attivo",
    "data_registrazione": "2017-06-30"
  },
  {
    "id": "USR-005",
    "nome": "Ahmed Al-Rashid",
    "ruolo": "Customs Specialist",
    "email": "a.alrashid@globalnexus.com",
    "ufficio": "Dubai, UAE",
    "stato": "Attivo",
    "data_registrazione": "2021-01-18"
  },
  {
    "id": "USR-006",
    "nome": "Lucia Fernandez",
    "ruolo": "Fleet Manager",
    "email": "l.fernandez@globalnexus.com",
    "ufficio": "Madrid, Spagna",
    "stato": "Attivo",
    "data_registrazione": "2019-09-12"
  },
  {
    "id": "USR-007",
    "nome": "David Okonkwo",
    "ruolo": "Warehouse Supervisor",
    "email": "d.okonkwo@globalnexus.com",
    "ufficio": "Lagos, Nigeria",
    "stato": "Inattivo",
    "data_registrazione": "2020-04-03"
  },
  {
    "id": "USR-008",
    "nome": "Elena Voronova",
    "ruolo": "Procurement Analyst",
    "email": "e.voronova@globalnexus.com",
    "ufficio": "Varsavia, Polonia",
    "stato": "Attivo",
    "data_registrazione": "2022-02-14"
  },
  {
    "id": "USR-009",
    "nome": "Carlos Mendoza",
    "ruolo": "Route Planner",
    "email": "c.mendoza@globalnexus.com",
    "ufficio": "Buenos Aires, Argentina",
    "stato": "Attivo",
    "data_registrazione": "2021-08-27"
  },
  {
    "id": "USR-010",
    "nome": "Priya Sharma",
    "ruolo": "IT Systems Manager",
    "email": "p.sharma@globalnexus.com",
    "ufficio": "Mumbai, India",
    "stato": "Attivo",
    "data_registrazione": "2020-11-09"
  },
  {
    "id": "USR-011",
    "nome": "Thomas Gruber",
    "ruolo": "Finance Controller",
    "email": "t.gruber@globalnexus.com",
    "ufficio": "Francoforte, Germania",
    "stato": "Attivo",
    "data_registrazione": "2018-05-21"
  },
  {
    "id": "USR-012",
    "nome": "Isabella Rossi",
    "ruolo": "Customer Relations Manager",
    "email": "i.rossi@globalnexus.com",
    "ufficio": "Milano, Italia",
    "stato": "Sospeso",
    "data_registrazione": "2023-01-05"
  },
  {
    "id": "USR-013",
    "nome": "Li Wei",
    "ruolo": "Trade Compliance Officer",
    "email": "l.wei@globalnexus.com",
    "ufficio": "Shanghai, Cina",
    "stato": "Attivo",
    "data_registrazione": "2019-12-01"
  },
  {
    "id": "USR-014",
    "nome": "Fatima Al-Zahrawi",
    "ruolo": "Logistics Analyst",
    "email": "f.alzahrawi@globalnexus.com",
    "ufficio": "Riyadh, Arabia Saudita",
    "stato": "Attivo",
    "data_registrazione": "2022-06-15"
  },
  {
    "id": "USR-015",
    "nome": "Andrei Popescu",
    "ruolo": "Transport Coordinator",
    "email": "a.popescu@globalnexus.com",
    "ufficio": "Bucarest, Romania",
    "stato": "Attivo",
    "data_registrazione": "2023-03-20"
  }
]
,
  orders: [
  {
    "id": "ORD-2024-0001",
    "cliente": "TechWorld GmbH",
    "origine": "Shanghai, Cina",
    "destinazione": "Amburgo, Germania",
    "peso_kg": 12500,
    "volume_m3": 48,
    "tipo_trasporto": "Marittimo",
    "stato": "In transito",
    "data_ordine": "2024-01-08",
    "data_consegna_prevista": "2024-02-15",
    "valore_usd": 85000
  },
  {
    "id": "ORD-2024-0002",
    "cliente": "AutoParts SpA",
    "origine": "Milano, Italia",
    "destinazione": "Toronto, Canada",
    "peso_kg": 3200,
    "volume_m3": 14,
    "tipo_trasporto": "Aereo",
    "stato": "Consegnato",
    "data_ordine": "2024-01-10",
    "data_consegna_prevista": "2024-01-13",
    "valore_usd": 42000
  },
  {
    "id": "ORD-2024-0003",
    "cliente": "MedSupply Corp",
    "origine": "Rotterdam, Paesi Bassi",
    "destinazione": "Lagos, Nigeria",
    "peso_kg": 8750,
    "volume_m3": 32,
    "tipo_trasporto": "Marittimo",
    "stato": "In attesa sdoganamento",
    "data_ordine": "2024-01-15",
    "data_consegna_prevista": "2024-02-28",
    "valore_usd": 134000
  },
  {
    "id": "ORD-2024-0004",
    "cliente": "Sunrise Electronics Ltd",
    "origine": "Shenzhen, Cina",
    "destinazione": "Los Angeles, USA",
    "peso_kg": 22100,
    "volume_m3": 86,
    "tipo_trasporto": "Marittimo",
    "stato": "In transito",
    "data_ordine": "2024-01-18",
    "data_consegna_prevista": "2024-03-05",
    "valore_usd": 290000
  },
  {
    "id": "ORD-2024-0005",
    "cliente": "PharmaBridge SA",
    "origine": "Basilea, Svizzera",
    "destinazione": "Singapore",
    "peso_kg": 650,
    "volume_m3": 4,
    "tipo_trasporto": "Aereo",
    "stato": "Consegnato",
    "data_ordine": "2024-01-20",
    "data_consegna_prevista": "2024-01-22",
    "valore_usd": 580000
  },
  {
    "id": "ORD-2024-0006",
    "cliente": "AgriExport Brasil",
    "origine": "Santos, Brasile",
    "destinazione": "Barcellona, Spagna",
    "peso_kg": 45000,
    "volume_m3": 185,
    "tipo_trasporto": "Marittimo",
    "stato": "In carico",
    "data_ordine": "2024-01-22",
    "data_consegna_prevista": "2024-03-10",
    "valore_usd": 67000
  },
  {
    "id": "ORD-2024-0007",
    "cliente": "FashionForward Group",
    "origine": "Hanoi, Vietnam",
    "destinazione": "Parigi, Francia",
    "peso_kg": 4200,
    "volume_m3": 22,
    "tipo_trasporto": "Aereo",
    "stato": "In transito",
    "data_ordine": "2024-01-25",
    "data_consegna_prevista": "2024-01-28",
    "valore_usd": 125000
  },
  {
    "id": "ORD-2024-0008",
    "cliente": "OilPipe Engineering",
    "origine": "Aberdeen, UK",
    "destinazione": "Abu Dhabi, UAE",
    "peso_kg": 78000,
    "volume_m3": 310,
    "tipo_trasporto": "Marittimo",
    "stato": "In preparazione",
    "data_ordine": "2024-01-28",
    "data_consegna_prevista": "2024-03-20",
    "valore_usd": 420000
  },
  {
    "id": "ORD-2024-0009",
    "cliente": "FoodTrade Pty Ltd",
    "origine": "Melbourne, Australia",
    "destinazione": "Tokyo, Giappone",
    "peso_kg": 16800,
    "volume_m3": 62,
    "tipo_trasporto": "Marittimo",
    "stato": "Consegnato",
    "data_ordine": "2023-12-15",
    "data_consegna_prevista": "2024-01-25",
    "valore_usd": 93000
  },
  {
    "id": "ORD-2024-0010",
    "cliente": "NordBau GmbH",
    "origine": "Stoccolma, Svezia",
    "destinazione": "Nairobi, Kenya",
    "peso_kg": 31000,
    "volume_m3": 124,
    "tipo_trasporto": "Marittimo",
    "stato": "In transito",
    "data_ordine": "2024-02-01",
    "data_consegna_prevista": "2024-03-30",
    "valore_usd": 188000
  },
  {
    "id": "ORD-2024-0011",
    "cliente": "LuxGoods Monaco",
    "origine": "Milano, Italia",
    "destinazione": "Dubai, UAE",
    "peso_kg": 890,
    "volume_m3": 6,
    "tipo_trasporto": "Aereo",
    "stato": "Consegnato",
    "data_ordine": "2024-02-03",
    "data_consegna_prevista": "2024-02-05",
    "valore_usd": 1250000
  },
  {
    "id": "ORD-2024-0012",
    "cliente": "Chemco India Pvt Ltd",
    "origine": "Mumbai, India",
    "destinazione": "Houston, USA",
    "peso_kg": 52000,
    "volume_m3": 205,
    "tipo_trasporto": "Marittimo",
    "stato": "Bloccato dogana",
    "data_ordine": "2024-02-05",
    "data_consegna_prevista": "2024-04-10",
    "valore_usd": 312000
  },
  {
    "id": "ORD-2024-0013",
    "cliente": "UrbanMobility SA",
    "origine": "Francoforte, Germania",
    "destinazione": "Santiago, Cile",
    "peso_kg": 9800,
    "volume_m3": 38,
    "tipo_trasporto": "Marittimo",
    "stato": "In preparazione",
    "data_ordine": "2024-02-08",
    "data_consegna_prevista": "2024-04-15",
    "valore_usd": 145000
  },
  {
    "id": "ORD-2024-0014",
    "cliente": "Digital Nomads Corp",
    "origine": "Taipei, Taiwan",
    "destinazione": "Amsterdam, Paesi Bassi",
    "peso_kg": 2100,
    "volume_m3": 11,
    "tipo_trasporto": "Aereo",
    "stato": "In transito",
    "data_ordine": "2024-02-10",
    "data_consegna_prevista": "2024-02-13",
    "valore_usd": 78000
  },
  {
    "id": "ORD-2024-0015",
    "cliente": "GreenEnergy Polska",
    "origine": "Danzica, Polonia",
    "destinazione": "Cape Town, Sudafrica",
    "peso_kg": 27500,
    "volume_m3": 108,
    "tipo_trasporto": "Marittimo",
    "stato": "In transito",
    "data_ordine": "2024-02-12",
    "data_consegna_prevista": "2024-04-20",
    "valore_usd": 234000
  }
]
,
  vehicles: [
  {
    "id": "GNL-TR-001",
    "tipo": "Camion",
    "modello": "Scania R450",
    "targa": "IT-GNL-0921",
    "capacita_ton": 24,
    "conducente": "Alessio Martini",
    "stato": "In servizio",
    "rotta_attuale": "Milano â€” Monaco di Baviera"
  },
  {
    "id": "GNL-TR-002",
    "tipo": "Camion",
    "modello": "Mercedes-Benz Actros 1853",
    "targa": "ES-GNL-1133",
    "capacita_ton": 25,
    "conducente": "Carlos Ruiz",
    "stato": "In manutenzione",
    "rotta_attuale": "Deposito Madrid"
  },
  {
    "id": "GNL-TR-003",
    "tipo": "Camion",
    "modello": "Volvo FH540",
    "targa": "DE-GNL-2244",
    "capacita_ton": 26,
    "conducente": "Klaus Hoffmann",
    "stato": "In servizio",
    "rotta_attuale": "Francoforte â€” Varsavia"
  },
  {
    "id": "GNL-TR-004",
    "tipo": "Camion",
    "modello": "DAF XF530",
    "targa": "FR-GNL-3311",
    "capacita_ton": 24,
    "conducente": "Jean-Pierre Moreau",
    "stato": "In servizio",
    "rotta_attuale": "Parigi â€” Barcellona"
  },
  {
    "id": "GNL-TR-005",
    "tipo": "Camion",
    "modello": "MAN TGX 26.500",
    "targa": "PL-GNL-4422",
    "capacita_ton": 24,
    "conducente": "Piotr Kowalski",
    "stato": "Fermo",
    "rotta_attuale": "Deposito Danzica"
  },
  {
    "id": "GNL-TR-006",
    "tipo": "Camion",
    "modello": "Iveco S-Way 570",
    "targa": "NL-GNL-5533",
    "capacita_ton": 25,
    "conducente": "Jan van der Berg",
    "stato": "In servizio",
    "rotta_attuale": "Rotterdam â€” Anversa"
  },
  {
    "id": "GNL-SH-001",
    "tipo": "Nave portacontainer",
    "modello": "MV Nexus Atlantic",
    "targa": "IMO 9812345",
    "capacita_ton": 55000,
    "conducente": "Capitano Erik Svensson",
    "stato": "In navigazione",
    "rotta_attuale": "Shanghai â€” Rotterdam"
  },
  {
    "id": "GNL-SH-002",
    "tipo": "Nave portacontainer",
    "modello": "MV Pacific Gateway",
    "targa": "IMO 9734211",
    "capacita_ton": 72000,
    "conducente": "Capitano Hiroshi Nakamura",
    "stato": "In porto",
    "rotta_attuale": "Porto di Singapore"
  },
  {
    "id": "GNL-SH-003",
    "tipo": "Nave cargo",
    "modello": "MV Indian Star",
    "targa": "IMO 9621008",
    "capacita_ton": 41000,
    "conducente": "Capitano Ravi Menon",
    "stato": "In navigazione",
    "rotta_attuale": "Dubai â€” Mumbai"
  },
  {
    "id": "GNL-SH-004",
    "tipo": "Nave Ro-Ro",
    "modello": "MV Gulf Express",
    "targa": "IMO 9589443",
    "capacita_ton": 28000,
    "conducente": "Capitano Ahmed Khalil",
    "stato": "In manutenzione",
    "rotta_attuale": "Cantiere navale Dubai"
  },
  {
    "id": "GNL-AV-001",
    "tipo": "Aereo cargo",
    "modello": "Boeing 747-8F",
    "targa": "N-GNL-001",
    "capacita_ton": 113,
    "conducente": "Comandante Sarah Mitchell",
    "stato": "In volo",
    "rotta_attuale": "Chicago â€” Francoforte"
  },
  {
    "id": "GNL-AV-002",
    "tipo": "Aereo cargo",
    "modello": "Airbus A330-200F",
    "targa": "F-GNL-002",
    "capacita_ton": 70,
    "conducente": "Comandante Pierre Leblanc",
    "stato": "In hangar",
    "rotta_attuale": "Aeroporto CDG, Parigi"
  }
]
,
  warehouses: [
  {
    "id": "DEP-001",
    "nome": "GlobalNexus Hub Milano",
    "indirizzo": "Via dell'Industria, 45",
    "citta": "Milano",
    "cap": "20142",
    "stato": "Lombardia",
    "nazione": "Italia",
    "telefono": "+39 02 8734 5600",
    "responsabile": "Marco Pellegrini",
    "capacita_pallet": 50000,
    "utilizzo_pct": 78,
    "certificazioni": "ISO 9001, GDP",
    "attivo": true
  },
  {
    "id": "DEP-002",
    "nome": "Frankfurt Logistics Center",
    "indirizzo": "IndustriestraÃŸe, 120",
    "citta": "Francoforte sul Meno",
    "cap": "60388",
    "stato": "Assia",
    "nazione": "Germania",
    "telefono": "+49 69 9834 7700",
    "responsabile": "Thomas Gruber",
    "capacita_pallet": 75000,
    "utilizzo_pct": 65,
    "certificazioni": "ISO 9001, AEO",
    "attivo": true
  },
  {
    "id": "DEP-003",
    "nome": "Rotterdam Port Warehouse",
    "indirizzo": "Maasvlakte 2, Terminal 7",
    "citta": "Rotterdam",
    "cap": "3199 LP",
    "stato": "Olanda Meridionale",
    "nazione": "Paesi Bassi",
    "telefono": "+31 10 7834 2900",
    "responsabile": "Jan van der Berg",
    "capacita_pallet": 120000,
    "utilizzo_pct": 88,
    "certificazioni": "ISO 9001, ISO 14001, AEO",
    "attivo": true
  },
  {
    "id": "DEP-004",
    "nome": "Singapore Global Hub",
    "indirizzo": "10 Pioneer Crescent, Jurong",
    "citta": "Singapore",
    "cap": "628557",
    "stato": "-",
    "nazione": "Singapore",
    "telefono": "+65 6734 8800",
    "responsabile": "Yuki Tanaka",
    "capacita_pallet": 85000,
    "utilizzo_pct": 91,
    "certificazioni": "ISO 9001, TAPA FSR A",
    "attivo": true
  },
  {
    "id": "DEP-005",
    "nome": "Dubai Trade Center Warehouse",
    "indirizzo": "Al Quoz Industrial Area 4, Street 17",
    "citta": "Dubai",
    "cap": "00000",
    "stato": "-",
    "nazione": "Emirati Arabi Uniti",
    "telefono": "+971 4 8834 5500",
    "responsabile": "Ahmed Al-Rashid",
    "capacita_pallet": 60000,
    "utilizzo_pct": 72,
    "certificazioni": "ISO 9001, GDP",
    "attivo": true
  },
  {
    "id": "DEP-006",
    "nome": "Shanghai Bonded Warehouse",
    "indirizzo": "No.1, Waigaoqiao Free Trade Zone",
    "citta": "Shanghai",
    "cap": "200131",
    "stato": "Shanghai",
    "nazione": "Cina",
    "telefono": "+86 21 5834 9900",
    "responsabile": "Li Wei",
    "capacita_pallet": 95000,
    "utilizzo_pct": 83,
    "certificazioni": "ISO 9001, C-TPAT",
    "attivo": true
  },
  {
    "id": "DEP-007",
    "nome": "Chicago Distribution Center",
    "indirizzo": "4500 West 51st Street",
    "citta": "Chicago",
    "cap": "60632",
    "stato": "Illinois",
    "nazione": "USA",
    "telefono": "+1 312 734 6600",
    "responsabile": "Robert Hayes",
    "capacita_pallet": 110000,
    "utilizzo_pct": 55,
    "certificazioni": "ISO 9001, C-TPAT",
    "attivo": true
  },
  {
    "id": "DEP-008",
    "nome": "Nairobi East Africa Hub",
    "indirizzo": "Mombasa Road, Industrial Area",
    "citta": "Nairobi",
    "cap": "00200",
    "stato": "Nairobi County",
    "nazione": "Kenya",
    "telefono": "+254 20 234 5600",
    "responsabile": "David Okonkwo",
    "capacita_pallet": 30000,
    "utilizzo_pct": 44,
    "certificazioni": "ISO 9001",
    "attivo": false
  }
]
,
  containers: [
  {
    "id": "CNT-2024-001",
    "sigla": "GNLU 224001-3",
    "tipo": "20ft Standard",
    "stato": "In viaggio",
    "posizione": "MV Nexus Atlantic â€” Oceano Indiano",
    "temperatura": "Ambiente",
    "peso_lordo_kg": 18450,
    "tara_kg": 2200,
    "sigillato": true,
    "contenuto": [
      { "descrizione": "Componenti elettronici Samsung", "quantita": "320 casse", "peso_kg": 4800 },
      { "descrizione": "Cavi industriali in rame", "quantita": "85 rotoli", "peso_kg": 6200 },
      { "descrizione": "Schede madri industriali", "quantita": "140 unitÃ ", "peso_kg": 1250 }
    ]
  },
  {
    "id": "CNT-2024-002",
    "sigla": "GNLU 224002-8",
    "tipo": "40ft High Cube",
    "stato": "In porto",
    "posizione": "Porto di Rotterdam â€” Banchina 14",
    "temperatura": "Ambiente",
    "peso_lordo_kg": 27800,
    "tara_kg": 3750,
    "sigillato": true,
    "contenuto": [
      { "descrizione": "Ricambi automotive Bosch", "quantita": "540 casse", "peso_kg": 12300 },
      { "descrizione": "Pneumatici Continental", "quantita": "200 unitÃ ", "peso_kg": 4800 },
      { "descrizione": "Olii lubrificanti industriali (fusti)", "quantita": "60 fusti da 200L", "peso_kg": 6950 }
    ]
  },
  {
    "id": "CNT-2024-003",
    "sigla": "GNLU 224003-5",
    "tipo": "Reefer 40ft",
    "stato": "In viaggio",
    "posizione": "MV Pacific Gateway â€” Mar Cinese Meridionale",
    "temperatura": "-18Â°C",
    "peso_lordo_kg": 22100,
    "tara_kg": 4200,
    "sigillato": true,
    "contenuto": [
      { "descrizione": "Carne bovina congelata (AUS)", "quantita": "480 casse da 20kg", "peso_kg": 9600 },
      { "descrizione": "Frutti di mare surgelati", "quantita": "320 casse da 10kg", "peso_kg": 3200 },
      { "descrizione": "Burro industriale (NZ)", "quantita": "250 blocchi da 25kg", "peso_kg": 6250 }
    ]
  },
  {
    "id": "CNT-2024-004",
    "sigla": "GNLU 224004-1",
    "tipo": "20ft Standard",
    "stato": "In deposito",
    "posizione": "DEP-006 â€” Shanghai Bonded Warehouse",
    "temperatura": "Ambiente",
    "peso_lordo_kg": 15900,
    "tara_kg": 2200,
    "sigillato": false,
    "contenuto": [
      { "descrizione": "Tessuti in fibra sintetica (balle)", "quantita": "180 balle", "peso_kg": 7200 },
      { "descrizione": "Accessori moda (scatole)", "quantita": "900 scatole", "peso_kg": 4500 },
      { "descrizione": "Pelletteria semilavorata", "quantita": "240 pezzi", "peso_kg": 2000 }
    ]
  },
  {
    "id": "CNT-2024-005",
    "sigla": "GNLU 224005-9",
    "tipo": "40ft Standard",
    "stato": "Sdoganamento",
    "posizione": "Porto di Lagos â€” Area doganale",
    "temperatura": "Ambiente",
    "peso_lordo_kg": 24600,
    "tara_kg": 3600,
    "sigillato": true,
    "contenuto": [
      { "descrizione": "Generatori elettrici industriali", "quantita": "12 unitÃ ", "peso_kg": 14400 },
      { "descrizione": "Pannelli solari fotovoltaici", "quantita": "300 pannelli", "peso_kg": 5400 },
      { "descrizione": "Cablaggio elettrico", "quantita": "40 bobine", "peso_kg": 2400 }
    ]
  },
  {
    "id": "CNT-2024-006",
    "sigla": "GNLU 224006-4",
    "tipo": "20ft Open Top",
    "stato": "In viaggio",
    "posizione": "MV Indian Star â€” Golfo di Aden",
    "temperatura": "Ambiente",
    "peso_lordo_kg": 19800,
    "tara_kg": 2300,
    "sigillato": false,
    "contenuto": [
      { "descrizione": "Macchinari agricoli (pezzi)", "quantita": "6 unitÃ  parziali", "peso_kg": 12000 },
      { "descrizione": "Attrezzatura per perforazione", "quantita": "4 set", "peso_kg": 5500 }
    ]
  },
  {
    "id": "CNT-2024-007",
    "sigla": "GNLU 224007-2",
    "tipo": "40ft High Cube",
    "stato": "In deposito",
    "posizione": "DEP-007 â€” Chicago Distribution Center",
    "temperatura": "Ambiente",
    "peso_lordo_kg": 18300,
    "tara_kg": 3750,
    "sigillato": true,
    "contenuto": [
      { "descrizione": "Prodotti cosmetici L'OrÃ©al", "quantita": "1200 cartoni", "peso_kg": 6000 },
      { "descrizione": "Articoli per la casa", "quantita": "800 cartoni", "peso_kg": 5600 },
      { "descrizione": "Giocattoli vari (assortiti)", "quantita": "400 casse", "peso_kg": 2750 }
    ]
  },
  {
    "id": "CNT-2024-008",
    "sigla": "GNLU 224008-7",
    "tipo": "Reefer 20ft",
    "stato": "In viaggio",
    "posizione": "GNL-TR-001 â€” Autostrada A4, Italia",
    "temperatura": "+4Â°C",
    "peso_lordo_kg": 11200,
    "tara_kg": 3100,
    "sigillato": true,
    "contenuto": [
      { "descrizione": "Prodotti farmaceutici (fiale)", "quantita": "2400 confezioni", "peso_kg": 3600 },
      { "descrizione": "Vaccini refrigerati", "quantita": "480 kit", "peso_kg": 960 },
      { "descrizione": "Reagenti di laboratorio", "quantita": "200 flaconi", "peso_kg": 400 }
    ]
  },
  {
    "id": "CNT-2024-009",
    "sigla": "GNLU 224009-6",
    "tipo": "20ft Standard",
    "stato": "Consegnato",
    "posizione": "Destinazione finale â€” Tokyo, Giappone",
    "temperatura": "Ambiente",
    "peso_lordo_kg": 14700,
    "tara_kg": 2200,
    "sigillato": false,
    "contenuto": [
      { "descrizione": "Materie prime chimiche (bombole)", "quantita": "80 bombole", "peso_kg": 9600 },
      { "descrizione": "Additivi alimentari", "quantita": "120 fusti", "peso_kg": 3600 }
    ]
  },
  {
    "id": "CNT-2024-010",
    "sigla": "GNLU 224010-0",
    "tipo": "45ft Pallet Wide",
    "stato": "In preparazione",
    "posizione": "DEP-003 â€” Rotterdam Port Warehouse",
    "temperatura": "Ambiente",
    "peso_lordo_kg": 29400,
    "tara_kg": 4100,
    "sigillato": false,
    "contenuto": [
      { "descrizione": "Componenti turbine eoliche", "quantita": "8 casse extra-large", "peso_kg": 16000 },
      { "descrizione": "Sensori industriali IoT", "quantita": "600 unitÃ ", "peso_kg": 900 },
      { "descrizione": "Cavi alta tensione", "quantita": "15 bobine", "peso_kg": 8400 }
    ]
  }
]
,
  departures: [
  {
    "id": "DEP-2024-001",
    "mezzo_id": "GNL-SH-001",
    "mezzo_nome": "MV Nexus Atlantic",
    "tipo_mezzo": "Nave portacontainer",
    "indirizzo": "Terminal APMT, Berth 6",
    "citta": "Shanghai",
    "cap": "200131",
    "stato": "Shanghai",
    "nazione": "Cina",
    "data_partenza": "2024-02-01",
    "ora_partenza": "06:00",
    "stato_partenza": "Partito",
    "ordini_trasportati": ["ORD-2024-0001", "ORD-2024-0004"]
  },
  {
    "id": "DEP-2024-002",
    "mezzo_id": "GNL-AV-001",
    "mezzo_nome": "Boeing 747-8F N-GNL-001",
    "tipo_mezzo": "Aereo cargo",
    "indirizzo": "O'Hare International Airport, Cargo Terminal 5",
    "citta": "Chicago",
    "cap": "60666",
    "stato": "Illinois",
    "nazione": "USA",
    "data_partenza": "2024-02-10",
    "ora_partenza": "22:30",
    "stato_partenza": "Partito",
    "ordini_trasportati": ["ORD-2024-0002", "ORD-2024-0011"]
  },
  {
    "id": "DEP-2024-003",
    "mezzo_id": "GNL-TR-001",
    "mezzo_nome": "Scania R450 IT-GNL-0921",
    "tipo_mezzo": "Camion",
    "indirizzo": "Via dell'Industria, 45 â€” DEP-001",
    "citta": "Milano",
    "cap": "20142",
    "stato": "Lombardia",
    "nazione": "Italia",
    "data_partenza": "2024-02-12",
    "ora_partenza": "05:30",
    "stato_partenza": "Partito",
    "ordini_trasportati": ["ORD-2024-0008"]
  },
  {
    "id": "DEP-2024-004",
    "mezzo_id": "GNL-SH-002",
    "mezzo_nome": "MV Pacific Gateway",
    "tipo_mezzo": "Nave portacontainer",
    "indirizzo": "Pasir Panjang Terminal, Gate 3",
    "citta": "Singapore",
    "cap": "118519",
    "stato": "-",
    "nazione": "Singapore",
    "data_partenza": "2024-02-14",
    "ora_partenza": "14:00",
    "stato_partenza": "In attesa",
    "ordini_trasportati": ["ORD-2024-0009", "ORD-2024-0007"]
  },
  {
    "id": "DEP-2024-005",
    "mezzo_id": "GNL-TR-003",
    "mezzo_nome": "Volvo FH540 DE-GNL-2244",
    "tipo_mezzo": "Camion",
    "indirizzo": "IndustriestraÃŸe, 120 â€” DEP-002",
    "citta": "Francoforte sul Meno",
    "cap": "60388",
    "stato": "Assia",
    "nazione": "Germania",
    "data_partenza": "2024-02-13",
    "ora_partenza": "07:00",
    "stato_partenza": "Partito",
    "ordini_trasportati": ["ORD-2024-0013"]
  },
  {
    "id": "DEP-2024-006",
    "mezzo_id": "GNL-AV-002",
    "mezzo_nome": "Airbus A330-200F F-GNL-002",
    "tipo_mezzo": "Aereo cargo",
    "indirizzo": "AÃ©roport Paris-Charles de Gaulle, Fret 7",
    "citta": "Parigi",
    "cap": "95700",
    "stato": "ÃŽle-de-France",
    "nazione": "Francia",
    "data_partenza": "2024-02-15",
    "ora_partenza": "10:15",
    "stato_partenza": "Programmato",
    "ordini_trasportati": ["ORD-2024-0005"]
  },
  {
    "id": "DEP-2024-007",
    "mezzo_id": "GNL-SH-003",
    "mezzo_nome": "MV Indian Star",
    "tipo_mezzo": "Nave cargo",
    "indirizzo": "Port of Jebel Ali, Terminal 2",
    "citta": "Dubai",
    "cap": "00000",
    "stato": "Dubai",
    "nazione": "Emirati Arabi Uniti",
    "data_partenza": "2024-02-10",
    "ora_partenza": "08:00",
    "stato_partenza": "Partito",
    "ordini_trasportati": ["ORD-2024-0012"]
  },
  {
    "id": "DEP-2024-008",
    "mezzo_id": "GNL-TR-004",
    "mezzo_nome": "DAF XF530 FR-GNL-3311",
    "tipo_mezzo": "Camion",
    "indirizzo": "Zone Logistique Gennevilliers, Rue des Chartrons 8",
    "citta": "Parigi",
    "cap": "92230",
    "stato": "ÃŽle-de-France",
    "nazione": "Francia",
    "data_partenza": "2024-02-11",
    "ora_partenza": "04:00",
    "stato_partenza": "Partito",
    "ordini_trasportati": ["ORD-2024-0007"]
  },
  {
    "id": "DEP-2024-009",
    "mezzo_id": "GNL-TR-006",
    "mezzo_nome": "Iveco S-Way NL-GNL-5533",
    "tipo_mezzo": "Camion",
    "indirizzo": "Maasvlakte 2, Terminal 7 â€” DEP-003",
    "citta": "Rotterdam",
    "cap": "3199 LP",
    "stato": "Olanda Meridionale",
    "nazione": "Paesi Bassi",
    "data_partenza": "2024-02-16",
    "ora_partenza": "09:00",
    "stato_partenza": "Programmato",
    "ordini_trasportati": ["ORD-2024-0010"]
  },
  {
    "id": "DEP-2024-010",
    "mezzo_id": "GNL-TR-005",
    "mezzo_nome": "MAN TGX PL-GNL-4422",
    "tipo_mezzo": "Camion",
    "indirizzo": "Wolny Street Port Complex, Gate B",
    "citta": "Danzica",
    "cap": "80-557",
    "stato": "Pomerania",
    "nazione": "Polonia",
    "data_partenza": "2024-02-17",
    "ora_partenza": "06:30",
    "stato_partenza": "Programmato",
    "ordini_trasportati": ["ORD-2024-0015"]
  },
  {
    "id": "DEP-2024-011",
    "mezzo_id": "GNL-TR-002",
    "mezzo_nome": "Mercedes Actros ES-GNL-1133",
    "tipo_mezzo": "Camion",
    "indirizzo": "Mercado Central de Transportes, Calle LogÃ­stica 22",
    "citta": "Madrid",
    "cap": "28022",
    "stato": "Comunidad de Madrid",
    "nazione": "Spagna",
    "data_partenza": "2024-02-20",
    "ora_partenza": "07:00",
    "stato_partenza": "In manutenzione",
    "ordini_trasportati": []
  },
  {
    "id": "DEP-2024-012",
    "mezzo_id": "GNL-AV-001",
    "mezzo_nome": "Boeing 747-8F N-GNL-001",
    "tipo_mezzo": "Aereo cargo",
    "indirizzo": "Frankfurt Airport, Cargo City South, Hub D",
    "citta": "Francoforte sul Meno",
    "cap": "60547",
    "stato": "Assia",
    "nazione": "Germania",
    "data_partenza": "2024-02-22",
    "ora_partenza": "01:45",
    "stato_partenza": "Programmato",
    "ordini_trasportati": ["ORD-2024-0014"]
  }
]
,
  destinations: [
  {
    "id": "DST-2024-001",
    "mezzo_id": "GNL-SH-001",
    "mezzo_nome": "MV Nexus Atlantic",
    "tipo_mezzo": "Nave portacontainer",
    "indirizzo": "ECT Delta Terminal, Amazonehaven 550",
    "citta": "Rotterdam",
    "cap": "3199 LD",
    "stato": "Olanda Meridionale",
    "nazione": "Paesi Bassi",
    "data_arrivo_prevista": "2024-02-15",
    "ora_arrivo_prevista": "08:00",
    "stato_arrivo": "In avvicinamento",
    "eta_aggiornata": "2024-02-15",
    "ordini_trasportati": ["ORD-2024-0001", "ORD-2024-0004"]
  },
  {
    "id": "DST-2024-002",
    "mezzo_id": "GNL-AV-001",
    "mezzo_nome": "Boeing 747-8F N-GNL-001",
    "tipo_mezzo": "Aereo cargo",
    "indirizzo": "Frankfurt Airport, Cargo City South",
    "citta": "Francoforte sul Meno",
    "cap": "60547",
    "stato": "Assia",
    "nazione": "Germania",
    "data_arrivo_prevista": "2024-02-11",
    "ora_arrivo_prevista": "09:45",
    "stato_arrivo": "Arrivato",
    "eta_aggiornata": "2024-02-11",
    "ordini_trasportati": ["ORD-2024-0002", "ORD-2024-0011"]
  },
  {
    "id": "DST-2024-003",
    "mezzo_id": "GNL-TR-001",
    "mezzo_nome": "Scania R450 IT-GNL-0921",
    "tipo_mezzo": "Camion",
    "indirizzo": "MÃ¼nchen Nord Logistikzentrum, Industriering 4",
    "citta": "Monaco di Baviera",
    "cap": "85748",
    "stato": "Baviera",
    "nazione": "Germania",
    "data_arrivo_prevista": "2024-02-13",
    "ora_arrivo_prevista": "14:00",
    "stato_arrivo": "In ritardo",
    "eta_aggiornata": "2024-02-14",
    "ordini_trasportati": ["ORD-2024-0008"]
  },
  {
    "id": "DST-2024-004",
    "mezzo_id": "GNL-SH-002",
    "mezzo_nome": "MV Pacific Gateway",
    "tipo_mezzo": "Nave portacontainer",
    "indirizzo": "Kobe Port Island, Terminal 3",
    "citta": "Kobe",
    "cap": "650-0024",
    "stato": "HyÅgo",
    "nazione": "Giappone",
    "data_arrivo_prevista": "2024-03-05",
    "ora_arrivo_prevista": "06:00",
    "stato_arrivo": "Programmato",
    "eta_aggiornata": "2024-03-05",
    "ordini_trasportati": ["ORD-2024-0009", "ORD-2024-0007"]
  },
  {
    "id": "DST-2024-005",
    "mezzo_id": "GNL-TR-003",
    "mezzo_nome": "Volvo FH540 DE-GNL-2244",
    "tipo_mezzo": "Camion",
    "indirizzo": "Centrum Logistyczne Warszawa, ul. Logistyczna 1",
    "citta": "Varsavia",
    "cap": "02-675",
    "stato": "Masovia",
    "nazione": "Polonia",
    "data_arrivo_prevista": "2024-02-14",
    "ora_arrivo_prevista": "16:00",
    "stato_arrivo": "Arrivato",
    "eta_aggiornata": "2024-02-14",
    "ordini_trasportati": ["ORD-2024-0013"]
  },
  {
    "id": "DST-2024-006",
    "mezzo_id": "GNL-AV-002",
    "mezzo_nome": "Airbus A330-200F F-GNL-002",
    "tipo_mezzo": "Aereo cargo",
    "indirizzo": "Changi Airport, Cargo Terminal T51",
    "citta": "Singapore",
    "cap": "819643",
    "stato": "-",
    "nazione": "Singapore",
    "data_arrivo_prevista": "2024-02-15",
    "ora_arrivo_prevista": "19:30",
    "stato_arrivo": "Programmato",
    "eta_aggiornata": "2024-02-15",
    "ordini_trasportati": ["ORD-2024-0005"]
  },
  {
    "id": "DST-2024-007",
    "mezzo_id": "GNL-SH-003",
    "mezzo_nome": "MV Indian Star",
    "tipo_mezzo": "Nave cargo",
    "indirizzo": "Jawaharlal Nehru Port, Gate 4, NSICT",
    "citta": "Mumbai",
    "cap": "400707",
    "stato": "Maharashtra",
    "nazione": "India",
    "data_arrivo_prevista": "2024-02-17",
    "ora_arrivo_prevista": "10:00",
    "stato_arrivo": "In avvicinamento",
    "eta_aggiornata": "2024-02-17",
    "ordini_trasportati": ["ORD-2024-0012"]
  },
  {
    "id": "DST-2024-008",
    "mezzo_id": "GNL-TR-004",
    "mezzo_nome": "DAF XF530 FR-GNL-3311",
    "tipo_mezzo": "Camion",
    "indirizzo": "Mercabarna, Carrer de la Llacuna s/n",
    "citta": "Barcellona",
    "cap": "08040",
    "stato": "Catalogna",
    "nazione": "Spagna",
    "data_arrivo_prevista": "2024-02-12",
    "ora_arrivo_prevista": "18:00",
    "stato_arrivo": "Arrivato",
    "eta_aggiornata": "2024-02-12",
    "ordini_trasportati": ["ORD-2024-0006"]
  },
  {
    "id": "DST-2024-009",
    "mezzo_id": "GNL-TR-006",
    "mezzo_nome": "Iveco S-Way NL-GNL-5533",
    "tipo_mezzo": "Camion",
    "indirizzo": "Antwerp Logistics Hub, Haven 750",
    "citta": "Anversa",
    "cap": "2030",
    "stato": "Anversa",
    "nazione": "Belgio",
    "data_arrivo_prevista": "2024-02-16",
    "ora_arrivo_prevista": "12:30",
    "stato_arrivo": "Programmato",
    "eta_aggiornata": "2024-02-16",
    "ordini_trasportati": ["ORD-2024-0010"]
  },
  {
    "id": "DST-2024-010",
    "mezzo_id": "GNL-TR-005",
    "mezzo_nome": "MAN TGX PL-GNL-4422",
    "tipo_mezzo": "Camion",
    "indirizzo": "Port of Cape Town, Ben Schoeman Dock",
    "citta": "Cape Town",
    "cap": "8001",
    "stato": "Western Cape",
    "nazione": "Sudafrica",
    "data_arrivo_prevista": "2024-04-20",
    "ora_arrivo_prevista": "08:00",
    "stato_arrivo": "Programmato",
    "eta_aggiornata": "2024-04-20",
    "ordini_trasportati": ["ORD-2024-0015"]
  },
  {
    "id": "DST-2024-011",
    "mezzo_id": "GNL-TR-002",
    "mezzo_nome": "Mercedes Actros ES-GNL-1133",
    "tipo_mezzo": "Camion",
    "indirizzo": "Port of Algeciras, Terminal Sur",
    "citta": "Algeciras",
    "cap": "11205",
    "stato": "Andalusia",
    "nazione": "Spagna",
    "data_arrivo_prevista": "-",
    "ora_arrivo_prevista": "-",
    "stato_arrivo": "Sospeso",
    "eta_aggiornata": "-",
    "ordini_trasportati": []
  },
  {
    "id": "DST-2024-012",
    "mezzo_id": "GNL-AV-001",
    "mezzo_nome": "Boeing 747-8F N-GNL-001",
    "tipo_mezzo": "Aereo cargo",
    "indirizzo": "Amsterdam Airport Schiphol, Cargo East",
    "citta": "Amsterdam",
    "cap": "1118 CP",
    "stato": "Olanda Settentrionale",
    "nazione": "Paesi Bassi",
    "data_arrivo_prevista": "2024-02-22",
    "ora_arrivo_prevista": "05:00",
    "stato_arrivo": "Programmato",
    "eta_aggiornata": "2024-02-22",
    "ordini_trasportati": ["ORD-2024-0014"]
  }
]

};
